### ISSUE TITLE
Update to Laravel 5.2

### ISSUE THREAD

**Issue by r0bdiabl0** [thinhbuzz/laravel-google-captcha#1]
Please update to be available for Laravel 5.2.*. Thank you.

**Comment by thinhbuzz** [comment]
now support laravel 5.2.*

**Comment by msankar1991** [comment]
While publish provider getting error on terminal with 5.2 version
```
  [ErrorException]
  array_merge(): Argument #2 is not an array
```

`cleared cache, composer update `also getting same above error.
