### ISSUE TITLE
Update test documentation for multiple captchas on a single page

### ISSUE THREAD

**Issue by gdejong** [thinhbuzz/laravel-google-captcha#10]
Hi there,

Let me start off by saying that I am very thankful for your recent update to this library to support multiple captchas on a single page!

I found however that I needed to update my integration tests as well with those new changes, and was wondering if this could be updated in the docs?

I have added three calls to my tests, could you tell me if this is the correct way to go? The first 2 `shouldReceive` calls are already documented by you. This is for testing a page that is using multiple captchas.

```
// prevent validation error on captcha
        CaptchaFacade::shouldReceive('verify')
            ->andReturn(true);
            
// provide hidden input for your 'required' validation
        CaptchaFacade::shouldReceive('display')
            ->andReturn('<input type="hidden" name="g-recaptcha-response" value="1" />');

CaptchaFacade::shouldReceive("displayJs");
CaptchaFacade::shouldReceive("displayMultiple");
CaptchaFacade::shouldReceive("multiple");
```

Cheers

**Comment by thinhbuzz** [comment]
you can create pull request for it ;)

**Comment by gdejong** [comment]
Sure, no problem :)
Just wanted to verify this is the way to go.

**Comment by gdejong** [comment]
See #11 

Cheers
