### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by hohl** [thinhbuzz/laravel-google-captcha#12]
Any plans on Laravel 5.5 support (especially [the new package auto-discovery](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518))?

**Comment by quanvo** [comment]
Seem, custom language is not working

**Comment by thinhbuzz** [comment]
let me check

**Comment by thinhbuzz** [comment]
@hohl have supported before
@quanvo fixed in ver 2.0.1, but i don't know why packagist does not update :(

**Comment by thinhbuzz** [comment]
haha, I forgot to update the composer.json 👎
