### ISSUE TITLE
Fatal Error Undefined Constant

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [thinhbuzz/laravel-google-captcha#15]
`Fatal error: Undefined constant 'Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider'`
from the readme, chaging this
`'Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider',`
to this 
`Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider::class,` seems to fix the problem.

**Comment by Briareos17** [comment]
@brian-lamb-software-engineer It is because you pasted `Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider` without quotes, so php recognize it as constant, not as string.
