### ISSUE TITLE
Error on file_get_contents()

### ISSUE THREAD

**Issue by StApostol** [thinhbuzz/laravel-google-captcha#17]
How I can set $requestMethod in __construct \ReCaptcha\ReCaptcha https://github.com/thinhbuzz/laravel-google-captcha/blob/master/src/Captcha.php#L207

Fix from google set socket as request method https://github.com/google/recaptcha/issues/36

**Comment by thinhbuzz** [comment]
sorry for too late response, issue can be fix by config ``get_request_method``. Please update package to 2.1.6
