### ISSUE TITLE
example reset captcha

### ISSUE THREAD

**Issue by DmitrySkibitsky** [thinhbuzz/laravel-google-captcha#24]
Please give an example of how you reset the captcha if there are several of them on the page. I have not tried it all the same.

**Comment by DmitrySkibitsky** [comment]
documentation:
```php
grecaptcha.reset(
opt_widget_id
)
````
 js:
```js
<script type="text/javascript">var buzzNoCaptchaOnLoadCallback = function() {grecaptcha.render('buzzNoCaptchaId_d649ff40713a7502e18656d207b2a63a', {"sitekey":"6LdVmDEUAAAAABEyMLp_V2Yr52KOYC19aovieDuE","size":"compact"});grecaptcha.render('buzzNoCaptchaId_89a13a9628c631ad4b732a0d4dd10059', {"sitekey":"6LdVmDEUAAAAABEyMLp_V2Yr52KOYC19aovieDuE","size":"compact"});};</script>

grecaptcha.reset('buzzNoCaptchaId_89a13a9628c631ad4b732a0d4dd10059');

````
error:

```js
Uncaught Error: Invalid reCAPTCHA client id: buzzNoCaptchaId_ada85a4805ccd5f01fbaef982e793c82
    at Object.Nr [as reset]
```

How to reset a specific captcha?

**Comment by DmitrySkibitsky** [comment]
We had to change the generation of js. Assign variable + i = grecaptcha.render. And after doing grecaptcha.reset (variable + i);

**Comment by DmitrySkibitsky** [comment]
after it must be added to the date attributes of the form. And by the form ID, generate a variable. And after creating a function in which the form will be transferred and a certain captcha will be reset on it.

**Comment by thinhbuzz** [comment]
i think will be create ``buzzNoCaptchaWidgetIds`` js variable and assign widget with key is html id.
i will flow [document](https://developers.google.com/recaptcha/docs/display#example)

Thanks you

**Comment by JanisE** [comment]
Looking forward to a fix. Cannot use this package while resetting not supported.

**Comment by thinhbuzz** [comment]
feature has been added in [v2.1.8](https://github.com/thinhbuzz/laravel-google-captcha/releases/tag/v2.1.8), you can try example on [examples folder](https://github.com/thinhbuzz/laravel-google-captcha/tree/v2.1.8/examples)
I hope useful to you

**Comment by thinhbuzz** [comment]
you want show multiple captcha on page and able reset it? check here [multiple.blade.php](https://github.com/thinhbuzz/laravel-google-captcha/blob/v2.1.8/examples/multiple.blade.php)

**Comment by DmitrySkibitsky** [comment]
I apologize. Everything, revised examples and changes. Thank you.

**Comment by DmitrySkibitsky** [comment]
You can close it.) The problem is solved.
