### ISSUE TITLE
How to show multiple Captcha on same page 

### ISSUE THREAD

**Issue by cent040** [thinhbuzz/laravel-google-captcha#3]

**Comment by gdejong** [comment]
Is there any news regarding this issue @thinhbuzz? Perhaps a solution would be to give the display method in Captcha.php a parameter to tell it to load the JS file or not?

**Comment by thinhbuzz** [comment]
@gdejong i will be check it

**Comment by thinhbuzz** [comment]
@gdejong you can get it on version 2.0
