### ISSUE TITLE
VueJs Conflict: script tag inside template

### ISSUE THREAD

**Issue by MaxChu23** [thinhbuzz/laravel-google-captcha#32]
I get an error when adding `Captcha::display()` to my view

> Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed

Because of `<script>` tag that has been injected along with captcha div. I've already tried to set `multiple` to true in config and adding `Captcha::displayJs()` in the end of `<body>` tag. It requires to create a `<script>` tag with callback `buzzNoCaptchaOnLoadCallback()` function inside that script and still not showing captcha (but eliminates the error message on loading)

**Comment by thinhbuzz** [comment]
can you show your code?

**Comment by MaxChu23** [comment]
That's a simple registration form:
``` html
@extends('layouts.main')

@section('content')
<div id="app">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="block">
        @include('components.errors')
        <div class="block-title t-center">@lang('menu.register')</div>
        <form action="/api/register" method="post" >
          {{ csrf_field() }}
            <div class="input-group input-group-center">
              <input class="input" type="text" name="email" placeholder="@lang('main.email')" value="{{ old('email') }}" >
              <input class="input" type="password" name="password" placeholder="@lang('main.password')" >
              <div class="inform-captcha">
                {!! Captcha::display() !!}
              </div>
              <button class="btn btn-lg btn-org width-full" >@lang('menu.register')</button>
            </div>
         </form>
       </div>
     </div>
  </div>
</div>
@endsection

@section('scripts')
  <script src="{{ mix('js/register.js') }}" ></script>
@endsection
```

**Comment by thinhbuzz** [comment]
you can try:

```php
{!! Captcha::display() !!}
```
and

```php
@section('scripts')
  <script src="{{ mix('js/register.js') }}" ></script>
{!! Captcha::displayJs() !!}
@endsection
```

**Comment by MaxChu23** [comment]
I've already tried that, but it requires to add callback that is displayed in the added `script` tag. However, when adding that callback, it's still not showing the captcha elements on page.

**Comment by thinhbuzz** [comment]
sorry for response to late. You don't need callback function, only you need is prevent add is when display captcha and move js link to end page

**Comment by airyng** [comment]
> sorry for response to late. You don't need callback function, only you need is prevent add is when display captcha and move js link to end page

I had a similar issue and your solve is working for me
