### ISSUE TITLE
Change language of captcha wrong ?

### ISSUE THREAD

**Issue by ducvu91** [thinhbuzz/laravel-google-captcha#33]
Hi,
I used your plugin, it perfect but when i change language, it sometime still wrong.
i config my language by vi, in both file config/captcha.php and change option in display lang => vi but sometime it still english. Can you help me fix this ?
pls and thanks you

https://photos.google.com/share/AF1QipMjw3iey2Y50l7zpoGjFXAm5EfLUKGYa3SqecL66ZIx-7xSgVzh0HKhOrLmo_mnhw?key=Ym9FZ1Z3VnhQWkxsMzUxNXBWekNYdHpBcTJwTnBn

**Comment by thinhbuzz** [comment]
i am going to check it!

**Comment by thinhbuzz** [comment]
iframe created automatic by reCapcha. Can you show your example source code?

**Comment by ducvu91** [comment]
code when i show 

config/captcha.php

return [
    'secret' => env('CAPTCHA_SECRET', 'xyz'),
    'sitekey' => env('CAPTCHA_SITEKEY', 'xyz'),
    /**
     * @var string|null Default ``null``.
     * Custom with function name (example customRequestCaptcha) or class@method (example \App\CustomRequestCaptcha@custom).
     * Function must be return instance, read more in folder ``examples``
     */
    'request_method' => null,
    'options' => [
        'multiple' => false,
        'lang' => 'vi',
    ],
    'attributes' => [
        'theme' => 'light'
    ],
];

in view :
{!! app('captcha')->display($attributes = ['data-callback' => 'onReCaptchaSuccess'], $options = ['lang'=> 'vi']) !!}

**Comment by thinhbuzz** [comment]
:( i can not reproduce issue

**Comment by nunomira** [comment]
This is also happening to me.
From my tests, it has to do with the languages that you have configured in your browser (tested both Firefox and Chrome)
My browsers are configured to English first, so I always get English, no matter the parameter I specify in the options.
If I change the browser preferences to another language, the captcha is displayed in that language, once again, ignoring the options.
