### ISSUE TITLE
fails() method are always true

### ISSUE THREAD

**Issue by hamid80386** [thinhbuzz/laravel-google-captcha#36]
I used of this rule to validate recaptcha:
```php
$validate = Validator::make($request->all(), [
            'g-recaptcha-response' => 'required|captcha',
            'name' => 'required',
        ]);
```
But this way always return fail, even when i checked recaptcha

```php
if ($validate->fails()) {
         var_dump($vlidate); 
         dd('fails');
}
```

When i checked passes() method is true and when i don't check, passes() return false, but in both sitiuation fails() method is true

**Comment by thinhbuzz** [comment]
please share your environment
