### ISSUE TITLE
file_get_contents() error not fixed at all?

### ISSUE THREAD

**Issue by Rishats** [thinhbuzz/laravel-google-captcha#37]
Laravel: 5.6
PHP: 7.2
"name": "buzz/laravel-google-captcha",
"version": "v2.1.10",

file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 

```[2019-01-23 10:05:41] production.ERROR: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 {"exception":"[object] (ErrorException(code: 0): file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 at /var/www/example.com/releases/6/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php:72)```

**Comment by thinhbuzz** [comment]
this is issue of google recapcha package. You must enable allow_url_fopen in php.ini
