### ISSUE TITLE
How to Set proxy in Laravel for buzz/laravel-google-captcha

### ISSUE THREAD

**Issue by susovancode14** [thinhbuzz/laravel-google-captcha#39]
How to set the proxy for calling buzz/laravel-google-captcha 

return [
    'secret' => env('CAPTCHA_SECRET', 'default_secret'),
    'sitekey' => env('CAPTCHA_SITEKEY', 'default_sitekey'),
    /**
     * @var string|null Default ``null``.
     * Custom with function name (example customRequestCaptcha) or class@method (example \App\CustomRequestCaptcha@custom).
     * Function must be return instance, read more in folder ``examples``
     */
    'request_method' => null,
    'options' => [
        'multiple' => false,
        'lang' => app()->getLocale(),
    ],
    'attributes' => [
        'theme' => 'light'
    ],
];

please help asap

**Comment by thinhbuzz** [comment]
You can set the proxy by setting `request_method `with your custom class, there is an existing class [CurlPost.php](https://github.com/google/recaptcha/blob/1.2.3/src/ReCaptcha/RequestMethod/CurlPost.php)
You can see here: https://github.com/google/recaptcha/issues/46#issuecomment-381646581
