### ISSUE TITLE
Support for invisible reCAPTCHAs

### ISSUE THREAD

**Issue by hohl** [thinhbuzz/laravel-google-captcha#44]
Are invisible reCAPTCHAs supported through this library?

I tried to use this library with the invisible data attribute (see v2 reCAPTCHA [docs](https://developers.google.com/recaptcha/docs/invisible) by Google):

```
{!! Captcha::display(['data-size' => 'invisible']) !!}
```

While this line hides the captcha, it also causes the validation to fail afterwards. Looking at Google documentation this flag should be the only change needed, but I can not figure out, why it does not work with this plugin. Any ideas? Or, maybe anybody here activly uses the invisible reCAPTCHAs already with this library?

**Comment by thinhbuzz** [comment]
I will take a look tomorrow

**Comment by thinhbuzz** [comment]
@hohl you can try this example
[invisible.blade.php](https://github.com/thinhbuzz/laravel-google-captcha-examples/commit/7e8bf75ada30687850f2fc920ac16802056ad3c0#diff-0929e771dc2fd74ae97a862360df3b0c)

**Comment by nelsonfsa** [comment]
Fixed it by adding this to my view:

grecaptcha.execute();

**Comment by hohl** [comment]
Thanks, yes that worked.
