### ISSUE TITLE
Multiple captcha on same page

### ISSUE THREAD

**Issue by estelleal** [thinhbuzz/laravel-google-captcha#47]
Hello,

I would like to add multiple captcha on multiple form but on the same page.
The problem is that the captcha JS file will be loaded X times as i include it one page instead of loading only one time.

I use this in my template : {!! Captcha::display([]) !!}

Someone already got this problem ?

Thanks

**Comment by thinhbuzz** [comment]
@estelleal did you checkout example [multiple.blade.php](https://github.com/thinhbuzz/laravel-google-captcha-examples/blob/master/resources/views/multiple.blade.php)?
