### ISSUE TITLE
Having Trouble

### ISSUE THREAD

**Issue by HDVinnie** [thinhbuzz/laravel-google-captcha#8]
So I started off running `composer require buzz/laravel-google-captcha` **install went fine.**

Im running laravel 5.4

Add ServiceProvider to the providers array in app/config/app.php.
'Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider',
_**(seeing im 5.4 and this doesnt exist I did the following)**_

Add ServiceProvider to the providers array in config/app.php.
**Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider::class,**

Then use Facade: add 'Captcha' => '\Buzz\LaravelGoogleCaptcha\CaptchaFacade', to the aliases array in app/config/app.php
_**(seeing im 5.4 and this doesnt exist I did the following)**_

 Facade: add **'Captcha' => \Buzz\LaravelGoogleCaptcha\CaptchaFacade::class,** to the aliases array in config/app.php

Then added my CAPTCHA_SECRET=[secret-key] CAPTCHA_SITEKEY=[site-key] with proper keys to my .env

Then placed {!! Captcha::display($attributes) !!} in my login.blade.php

When I goto login page I get the following error:
`Undefined variable: attributes (View: /home/UNIT3D_2.0/resources/views/user/login.blade.php)`

**Comment by thinhbuzz** [comment]
Please read it: [How to use it](https://github.com/thinhbuzz/laravel-google-captcha#usage):
With

```php
$attributes = [
	'data-theme' => 'dark',
	'data-type'	=>	'audio',
];
```

More infomation on [google recaptcha document](https://developers.google.com/recaptcha/docs/display)

It mean:

```php
{!! Captcha::display( [
	'data-theme' => 'dark',
	'data-type'	=>	'audio',
]) !!}
```

**Comment by HDVinnie** [comment]
I see I assumed `{!! Captcha::display($attributes) !!}` would have a default value of the light theme. and would use something like `{!! Captcha::display( ['data-theme' => 'dark',]) !!}` if you wanted to use dark theme instead

**Comment by nillegal** [comment]
Tested on 2 different applications; on the one it works fine, on the other one it doesn't add the `data-sitekey`. Where could be the problem? Already tried using Facade.
