### ISSUE TITLE
Getting JS error : Uncaught Error: ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by asmafarhat2006** [thinhbuzz/laravel-google-captcha#9]
I added the recaptcha on the page and getting this error. 
any ideas?

**Comment by lvthinh1487** [comment]
> You are loading the google recaptcha library twice.

[Error: ReCAPTCHA placeholder element must be empty](http://stackoverflow.com/questions/37021241/error-recaptcha-placeholder-element-must-be-empty)

**Comment by asmafarhat2006** [comment]
@lvthinh1487  yes i knew that. i removed the JS file ,because your package is already adding it.
But im still getting the same error
